---
title: "extract_env_for_ssms.Rmd"
author: "Dana K Briscoe"
date: "`r Sys.Date()`"
output: html_document
params: 
    ncpath: "/Users/briscoedk/dbriscoe@stanford.edu - Google Drive/My Drive/ncdf"
    ftype: "rds"
    # ftype: "csv"
    dataset: stretch
    # dataset: historic
    # envs: !r c('sst_NOAA_DHW_monthly_Lon0360', 'multi-4km_P1M_CHL')
    # envs: !r c('hycom_uv', 'dhw_5km')
    envs: !r c('globtotal', 'hycom_uv', 'dhw_5km', 'multi-4km_P1M_CHL', 'multi-4km_P1D')
    lon_range: !r tibble::tibble(min=-180, max=-110)
    # lon_range: 'NA'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load libraries
library(tidyverse)
library(glue)
library(here)
```

```{r}
# source xtracto local source ---------------------------------
# source('~/Dropbox/RESEARCH/CODES/R_codes/xtractomatic/Xtracto_Local_NPAC.R')   
source('~/Dropbox/RESEARCH/CODES/R_codes/xtractomatic/Xtracto_Local_NPAC_STRETCH.R')   
```

```{r}
# source Scripts -----
source(here("R", "00_prep_cohort_data_helper_functions.R"))
```

```{r}
# specifcy function: FYI, this is a modified function from orig XTRACTO LOCAL ----
getDateRangeX <- function(inpts, ncIn){
    parsedt <- vector(mode='character', length(ncIn))
    for (j in 1:length(ncIn)){
        nc <- ncIn[j]
        parsename <- unlist(strsplit(nc,'_'))
        parsedt[j] <- substr(parsename[abs(length(parsename))],1,10)
    }
    startD <- format(as.POSIXct(min(inpts$dt), tz='UTC'), '%Y-%m-%d')
    print(paste('Ptsfile start', startD))
    endD <- format(as.POSIXct(max(inpts$dt), tz='UTC'), '%Y-%m-%d')
    print(paste('Ptsfile end', endD))
    startfile <- which(abs(as.Date(parsedt)-as.Date(startD)) == min(abs(as.Date(parsedt)-as.Date(startD))))[1]-1
    endfile <- which(abs(as.Date(endD)-as.Date(parsedt)) == min(abs(as.Date(endD)-as.Date(parsedt))))[1]
    dtIn <- ncIn[startfile:endfile]
}
```

## LOAD DATA ----

```{r}

# Prep input data set
tag_fpath <- file.path(here() %>% dirname(), 'cc-process-ssm', 'data', 'ssm_rw', params$dataset)

if(params$ftype == 'csv'){

    flist = list.files(tag_fpath, pattern = ".csv",full.names=T)
    
    # read in tags
    tag_list <-
        lapply(flist, function(i){
            read.csv(i, header=TRUE)
        })
    
    # convert to df 
    tag_df = data.table::rbindlist(tag_list) %>%
                as_tibble() %>%
                mutate(dt = as.Date(date)) %>%
                mutate(group = case_when(
                date < ymd_hms('2023-01-01 00:00:00')  ~ "historic", 
                date >= ymd_hms('2023-07-01 00:00:00') & 
                    date < ymd_hms('2024-05-01 00:00:00') ~ "cohort1",
                date >= ymd_hms('2024-07-01 00:00:00') ~ "cohort2",
                TRUE ~ NA))

} else if(params$ftype == "rds"){
    
    flist = 
        list.files(here('data', 'processed'), 
                  pattern=glue("{params$dataset}.*{params$ftype}"), full.names=T)
       
    tag_list <-
        lapply(flist, function(i){
            readRDS(i,)
        })
       
    tag_df = data.table::rbindlist(tag_list) %>%
                as_tibble() %>%
                mutate(dt = as.Date(date))
}
```


```{r}
# Rename for env extraction abstraction
obsdata = tag_df |> 
    mutate(month = month(date),
           year = year(date)) #|>
    # filter(month >= 9 & month <dhw_5km= 10)
    # filter(year == 2025)

```

# LIST NETCDFs -----

```{r}
list.ncs <- list.files(params$ncpath, full.names=T, recursive = T)

obsdata$X <- seq(1,nrow(obsdata))

obsdata$dt <- as.POSIXct(paste(obsdata$date,'12:00:00'),tz='UTC')

obsdata$dtime<-as.POSIXct(obsdata$date,origin="1970-01-01",tz='UTC')

cat('obs date range:')
range(obsdata$dtime |> as.Date())

cat('\nobs lon range:')
range(obsdata$lon)  

```

<!-- ## let's do this.... -->

<!-- ## MONTHLYS ----------------------------------------------------------- -->
# 1. SST ----

### SST | Monthly (Coral Reef Watch)
```{r, include=FALSE}
## CRW SST (Monthly, 5km spatial res). Product is 0/360)

if('sst_NOAA_DHW_monthly_Lon0360' %in% params$envs){
    
    # make lon 360
    obsdata <- obsdata %>%
    mutate(lon = make360(lon))
    
    # get file names
    filenames<-grep("sst_NOAA_DHW_monthly_Lon0360",list.ncs, fixed = TRUE)  
    sstfiles<-list.ncs[filenames]
    varname<-"sea_surface_temperature";  mnradius<- 0.25; sdradius<- 1; alt<-1
    
    sstfilesIn <- getDateRangeX(inpts=obsdata,ncIn=sstfiles) 
    
    # extract 
    sstmean <- rbindlist(lapply(sstfilesIn,
                        FUN=getvar,varname=varname,
                        ptsfile=obsdata,pt.radius=mnradius),
                        fill=TRUE)
    
    # add to obsdata
    obsdata$sst_monthly_new_mean<-rep(NA, length(obsdata[,1])); 
    obsdata$sst_monthly_new_mean_sd<-rep(NA, length(obsdata[,1]))
               
    obsdata$sst_monthly_new_mean[sstmean$X]<-sstmean$sea_surface_temperature_mean
    obsdata$sst_monthly_new_mean_sd[sstmean$X]<-sstmean$sea_surface_temperature_sd
    
    # preview results
    head(obsdata); tail(obsdata)
    range(obsdata$sst_monthly_new_mean, na.rm=T)
    
    # clean ws
    rm(sstmean); rm(sstfilesIn)
    
    # return back to -180/180
    obsdata <- obsdata %>%
    mutate(lon = make180(lon))

}
```


### SST | Daily (Coral Reef Watch)
```{r}
## CRW DHW SST (Daily, 5km spatial res). Product is -180/180)

if('dhw_5km' %in% params$envs){
    
    # get file names
    filenames<-grep("sst_dhw_5km",list.ncs, fixed = TRUE)  
    sstfiles<-list.ncs[filenames]
    varname<-"CRW_SST";  mnradius<- 0.25; sdradius<- 1; alt<-1
    
    sstfilesIn <- getDateRangeX(inpts=obsdata,ncIn=sstfiles) 
    
    # extract 
    sstmean <- rbindlist(lapply(sstfilesIn,
                        FUN=getvar,varname=varname,
                        ptsfile=obsdata,pt.radius=mnradius),
                        fill=TRUE)
    
    # add to obsdata
    obsdata$sst_daily_new_mean<-rep(NA, length(obsdata[,1])); 
    obsdata$sst_daily_new_mean_sd<-rep(NA, length(obsdata[,1]))
               
    obsdata$sst_daily_new_mean[sstmean$X]<-sstmean$CRW_SST_mean
    obsdata$sst_daily_new_mean_sd[sstmean$X]<-sstmean$CRW_SST_sd

    # preview results    
    head(obsdata); tail(obsdata)
    range(obsdata$sst_daily_new_mean, na.rm=T)
    
    # clean ws
    rm(sstmean); rm(sstfilesIn)

}
```


### SSTA | Daily (Coral Reef Watch)
```{r}

## CRW DHW SST (Daily, 5km spatial res). Product is -180/180)

## DKB NOTE: Jul 2025 -- No hay historic SSTA ncdf daily files. Will need to download in order to extract 

if('dhw_5km' %in% params$envs){
    
    # get file names
    filenames<-grep("ssta_dhw_5km",list.ncs, fixed = TRUE)  
    sstafiles<-list.ncs[filenames]
    varname<-"CRW_SSTANOMALY";  mnradius<- 0.25; sdradius<- 1; alt<-1
    
    sstafilesIn <- getDateRangeX(inpts=obsdata,ncIn=sstafiles) 
    
    # extract 
    sstamean <- rbindlist(lapply(sstafilesIn,
                        FUN=getvar,varname=varname,
                        ptsfile=obsdata,pt.radius=mnradius),
                        fill=TRUE)
    
    # add to obsdata
    obsdata$ssta_daily_new_mean<-rep(NA, length(obsdata[,1])); 
    obsdata$ssta_daily_new_mean_sd<-rep(NA, length(obsdata[,1]))
               
    obsdata$ssta_daily_new_mean[sstamean$X]<-sstamean$CRW_SSTANOMALY_mean
    obsdata$ssta_daily_new_mean_sd[sstamean$X]<-sstamean$CRW_SSTANOMALY_sd
    
    # preview results    
    head(obsdata); tail(obsdata)
    range(obsdata$ssta_daily_new_mean, na.rm=T)
    
    # clean ws
    rm(sstamean); rm(sstafilesIn)

}

```

# 2. CURRENTS ----

### HYCOM | Daily
```{r, hycom-uv}

## Daily Hycom U, V Product is 0/360)

if('hycom_uv' %in% params$envs){
    
    # make lon 360
    obsdata <- obsdata %>%
    mutate(lon = make360(lon))
    
    # set up empty cols    
    obsdata$hycom_u_daily_new_mean<-rep(NA, length(obsdata[,1])); 
    obsdata$hycom_u_daily_new_mean_sd<-rep(NA, length(obsdata[,1]))
    
    obsdata$hycom_v_daily_new_mean<-rep(NA, length(obsdata[,1])); 
    obsdata$hycom_v_daily_new_mean_sd<-rep(NA, length(obsdata[,1]))
    
    # varnames to extract
    varstring = c('GLBy0', 'ESPC-D-V02')

    
        for(v in varstring){
           # get file names
            hycomfiles <- list.files(params$ncpath, pattern = v, full.names=T, recursive = T) 
            hycomfiles <- hycomfiles[order(basename(hycomfiles))]
                
            ## u --
            if(v == "ESPC-D-V02") {
                hycomfiles_u = hycomfiles %>% .[grepl("u3z", .)]
                hycomfilesIn = getDateRangeX(inpts=obsdata, ncIn=hycomfiles_u) 
            } else {
                hycomfilesIn <- getDateRangeX(inpts=obsdata, ncIn=hycomfiles) 
            }
            
            varname<-"water_u";  mnradius<- 0.25; sdradius<- 1; alt<-1
    
            # extract 
            umean <- rbindlist(lapply(hycomfilesIn, FUN=getvar,varname=varname,
                                      ptsfile=obsdata, pt.radius=mnradius),
                                      fill=TRUE)
            
            # add to obsdata
            obsdata$hycom_u_daily_new_mean[umean$X]<-umean$water_u_mean
            obsdata$hycom_u_daily_new_mean_sd[umean$X]<-umean$water_u_sd
            
            # clean ws
            rm(umean) 
        
            
            ## v --
            if(v == "ESPC-D-V02") {
                hycomfiles_v = hycomfiles %>% .[grepl("v3z", .)]
                hycomfilesIn = getDateRangeX(inpts=obsdata, ncIn=hycomfiles_v) 
            } else {
                hycomfilesIn <- getDateRangeX(inpts=obsdata, ncIn=hycomfiles) 
            }
        
            varname<-"water_v";  mnradius<- 0.25; sdradius<- 1; alt<-1
            
            # extract 
            vmean <- rbindlist(lapply(hycomfilesIn, FUN=getvar,varname=varname,
                                      ptsfile=obsdata, pt.radius=mnradius),
                                      fill=TRUE)
            
            # add to obsdata
            obsdata$hycom_v_daily_new_mean[vmean$X]<-vmean$water_v_mean
            obsdata$hycom_v_daily_new_mean_sd[vmean$X]<-vmean$water_v_sd
            
            # clean ws
            rm(vmean)
          
            rm(hycomfilesIn, hycomfiles)
            
        } # end for varstring 
    

   # preview results  
    head(obsdata)
    range(obsdata$hycom_u_daily_new_mean, na.rm=T)
    range(obsdata$hycom_v_daily_new_mean, na.rm=T)
    
    # return back to -180/180
    obsdata <- obsdata %>%
    mutate(lon = make180(lon))


} # end if hycom_uv

```


### GlobTotal | Daily (u,v)
```{r, globtotal}

# Copernicus global total ocean current (incl ekman & geostrophic components; daily, 0.25 x 0.25 degree spatial res). Product in -180/180


if('globtotal' %in% params$envs){
    
    # get file names
    filenames<-grep("cmems_obs-mob_glo_phy-cur_my_0.25deg_P1D-m",list.ncs)

    globtotalfiles<-list.ncs[filenames]

    varnames = c('uo', 'vo')
    mnradius<- 1; sdradius<- 1; alt<-1
    
    globtotalfilesIn <- getDateRangeX(inpts=obsdata,ncIn=globtotalfiles)
    
    # extract 
    ## uo ---
    globtotal_uo_mean <- rbindlist(lapply(globtotalfilesIn,FUN=getvar,varname=varnames[1],
                                       ptsfile=obsdata,
                                       pt.radius=mnradius,alt=alt),
                                       fill=TRUE)
    
    # add to obsdata    
    obsdata$globtotal_uo_new_mean<-rep(NA, length(obsdata[,1]))
    obsdata$globtotal_uo_new_mean[globtotal_uo_mean$X]<-globtotal_uo_mean$uo_mean
    
    
    ## vo ---
    globtotal_vo_mean <- rbindlist(lapply(globtotalfilesIn,FUN=getvar,varname=varnames[2],
                                       ptsfile=obsdata,
                                       pt.radius=mnradius,alt=alt),
                                       fill=TRUE)
    
    
    # add to obsdata
    obsdata$globtotal_vo_new_mean<-rep(NA, length(obsdata[,1]))
    obsdata$globtotal_vo_new_mean[globtotal_vo_mean$X]<-globtotal_vo_mean$vo_mean
    
   # preview results  
    head(obsdata)
    range(obsdata$globtotal_uo_new_mean, na.rm=T)
    range(obsdata$globtotal_vo_new_mean, na.rm=T)
    
    # clean ws
    rm(globtotal_uo_mean, globtotal_vo_mean); rm(globtotalfilesIn)

}

```

```{r, prep-obsdata-for-chlx}
# # FYI all CHL PRODUCTS ARE -180/180
# obsdata <- obsdata %>%
#     mutate(lon = make180(lon))

```

# 3. CHLA ----

### GlobColour | Monthly
```{r, globcolour-mday, warning=FALSE}

# Copernicus Global Ocean Colour (Monthly, 4km spatial res). Product in -180/180

invisible(
if('multi-4km_P1M_CHL' %in% params$envs){
    
    # get file names - note specis subfolder 
    globcolour_list.ncs <- list.files(str_c(params$ncpath,
                                            '/npac/cmems_globcolour_expanded_lats'), 
                                            full.names=T, recursive = T)
    
    # get file names
    filenames<-grep("multi-4km_P1M_CHL",globcolour_list.ncs)
    filenames<-grep("cmems_obs-oc_glo_bgc-plankton_my_l4-multi-4km_P1M_CHL",
                     globcolour_list.ncs)

    chlfiles<-globcolour_list.ncs[filenames]
    
    varname<-"CHL";  mnradius<- 1; sdradius<- 1; alt<-1
    chlfilesIn <- getDateRangeX(inpts=obsdata,ncIn=chlfiles)
    
    # extract 
    globcolourmean <- rbindlist(lapply(chlfilesIn,FUN=getvar,varname=varname,
                                       ptsfile=obsdata,
                                       pt.radius=mnradius,alt=alt),
                                       fill=TRUE)
    
    # add to obsdata
    obsdata$globcolour_new_mean<-rep(NA, length(obsdata[,1]))
    obsdata$globcolour_new_mean[globcolourmean$X]<-globcolourmean$CHL_mean
    
    # preview results
    head(obsdata)
    range(obsdata$globcolour_new_mean, na.rm=T)
    
    # clean ws
    rm(globcolourmean); rm(chlfilesIn)

}
)
```

### GlobColour | Daily
```{r, globcolour-day, warning=FALSE}

# Copernicus Global Ocean Colour (Monthly, 4km spatial res). Product in -180/180

invisible(
if('multi-4km_P1D' %in% params$envs){
    
    # get file names - note specis subfolder 
    globcolour_list.ncs <- list.files(str_c(params$ncpath,
                                            '/npac/cmems_globcolour_expanded_lats/extra_expansion'), 
                                            full.names=T, recursive = T)
    
    # get file names
    filenames<-grep("multi-4km_P1D",globcolour_list.ncs)
    filenames<-grep("cmems_obs-oc_glo_bgc-plankton_my_l4-gapfree-multi-4km_P1D_CHL_",
                     globcolour_list.ncs)

    chlfiles<-globcolour_list.ncs[filenames]
    
    varname<-"CHL_daily";  mnradius<- 1; sdradius<- 1; alt<-1
    chlfilesIn <- getDateRangeX(inpts=obsdata,ncIn=chlfiles)
    
    # extract 
    globcolourmean <- rbindlist(lapply(chlfilesIn,FUN=getvar,varname=varname,
                                       ptsfile=obsdata,
                                       pt.radius=mnradius,alt=alt),
                                       fill=TRUE)
    
    # add to obsdata
    obsdata$globcolour_new_mean<-rep(NA, length(obsdata[,1]))
    obsdata$globcolour_new_mean[globcolourmean$X]<-globcolourmean$CHL_mean
    
    # preview results
    head(obsdata)
    range(obsdata$globcolour_new_mean, na.rm=T)
    
    # clean ws
    rm(globcolourmean); rm(chlfilesIn)

}
)
```


### SEAWiFS | Monthly 
```{r, seawifs-mday}

# Seawifs Chl-a (Monthly from 9/1997 - 12/2003, 0.1 degree spatial res). Product in -180/180

if('erdSW2018chlamday' %in% params$envs){
    
    # get file names
    filenames<-grep("erdSW2018chlamday",list.ncs)

    chlfiles<-list.ncs[filenames]
    
    varname<-"chlorophyll";  mnradius<- 1; sdradius<- 1; alt<-1
    chlfilesIn <- getDateRangeX(inpts=obsdata,ncIn=chlfiles)
    
    # extract 
    seawifsmean <- rbindlist(lapply(chlfilesIn,FUN=getvar,varname=varname,
                                    ptsfile=obsdata,pt.radius=mnradius,alt=alt),
                                    fill=TRUE)
    
    # add to obsdata
    obsdata$seawifs_new_mean<-rep(NA, length(obsdata[,1]))
    obsdata$seawifs_new_mean[seawifsmean$X]<-seawifsmean$chlorophyll_mean
    
    # preview results
    head(obsdata)
    range(obsdata$seawifs_new_mean, na.rm=T)
    
    # clean ws
    rm(seawifsmean); rm(chlfilesIn)

}


```


### MODIS | Monthly
```{r, modis-mday}

# MODIS Chl-a (Monthly from 1/2004 - 5/2022, 4km spatial res). Product in -180/180

if('erdMH1chlamday' %in% params$envs){

    # get file names
    filenames<-grep("erdMH1chlamday",list.ncs)
    chlfiles<-list.ncs[filenames]
    
    varname<-"chlorophyll";  mnradius<- 1; sdradius<- 1; alt<-1
    chlfilesIn <- getDateRangeX(inpts=obsdata,ncIn=chlfiles)
    
    # extract 
    modismean <- rbindlist(lapply(chlfilesIn,FUN=getvar,varname=varname,
                                  ptsfile=obsdata,pt.radius=mnradius,alt=alt),
                                  fill=TRUE)
    
    # add to obsdata
    obsdata$modis_new_mean<-rep(NA, length(obsdata[,1]))
    obsdata$modis_new_mean[modismean$X]<-modismean$chlorophyll_mean
    
    # preview results
    head(obsdata)
    range(obsdata$modis_new_mean, na.rm=T)
    
    # clean ws
    rm(modismean); rm(chlfilesIn)

}

```


### VIIRS | Monthly
```{r, viirs-mday}

# VIIRS Chl-a (Monthly from 1/2012 - 2/2024, 4km spatial res). Product in -180/180

if('nesdisVHNSQchlaMonthly_' %in% params$envs){

    # get file names
    filenames<-grep("nesdisVHNSQchlaMonthly_",list.ncs)
    
    chlfiles<-list.ncs[filenames]
    
    varname<-"chlor_a";  mnradius<- 0.25; sdradius<- 1; alt<-1
    chlfilesIn <- getDateRangeX(inpts=obsdata,ncIn=chlfiles)
    
    # extract 
    viirsmean <- rbindlist(lapply(chlfilesIn,FUN=getvar,varname=varname,
                                  ptsfile=obsdata,pt.radius=mnradius,alt=alt),
                                  fill=TRUE)
    
    # add to obsdata
    obsdata$viirs_new_mean<-rep(NA, length(obsdata[,1]))
    obsdata$viirs_new_mean[viirsmean$X]<-viirsmean$chlor_a_mean
    
    # preview results
    head(obsdata)
    range(obsdata$viirs_new_mean, na.rm=T)
    
    # clean ws
    rm(viirsmean); rm(chlfilesIn)

}
```


# CALC % MISSING DATA ----
```{r}
print('% data missing: ')

(colMeans(is.na(obsdata)))*100
```

### FILL CHLA GAPS
```{r, fill-chlmday-gaps}



if('seawifs_new_mean' %in% names(obsdata) & 'modis_new_mean' %in% names(obsdata) & 'seawifs_new_mean' %in% names(obsdata)){
    ## Assign new chl col var to hold merged products
    obsdata$chl_mean <- as.numeric(obsdata$modis_new_mean)    
    
    for (x in 1:dim(obsdata)[1]){
        if (is.na(obsdata$chl_mean[x])) {obsdata$chl_mean[x] <- obsdata$seawifs_new_mean[x]} # merge modis + seawifs
    }

    for (x in 1:dim(obsdata)[1]){
        if (is.na(obsdata$chl_mean[x])) {obsdata$chl_mean[x] <- obsdata$viirs_new_mean[x]}   # merge modis + seawifs + viirs
    }
} else if('globcolour_new_mean' %in% names(obsdata)){
    
    obsdata$chl_mean <- as.numeric(obsdata$globcolour_new_mean) 
}  

## Re-check % gappiness
(length(which(is.na(obsdata$chl_mean)))/nrow(obsdata))*100  ## 23.9% missing - bledno chl; [1] 3.332511$ missing glob colour

na_by_cols <- lapply(obsdata, function(x) sum(is.na(x)))

(na_by_cols$chl_mean / nrow(obsdata)) * 100

```

```{r}
# cross check all rows - run in console
# skimr::skim(obsdata)

```

```{r}
# Important Interim Step before saving: Return lons to 0 to 360
if(min(obsdata$lon) < 0){
    obsdata <- obsdata %>%
        mutate(lon = make360(lon))
}

```

```{r}
# fname = glue::glue("indiv_tags_df_sept1997_mar2024_180_140W_xtracted_env_ms", ,".rds")

# fname = glue::glue("{params$dataset}_xtracted_{params$envs}_{Sys.Date()}.rds")
fname = glue::glue("{params$dataset}_xtracted_envs_{Sys.Date()}.rds")
saveRDS(obsdata, file = file.path(here() %>% dirname(), 'cc-stretch-dynamic-tch',
                                  'data', 'processed', fname))

```
